services:
  - type: web
    name: ai-job-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        fromGroup: supabase
      - key: SUPABASE_ANON_KEY
        fromGroup: supabase
      - key: SUPABASE_SERVICE_KEY
        fromGroup: supabase
      - key: GEMINI_API_KEY
        fromGroup: gemini
